# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78b671aa68b662df86b5f09123613180cdece94956d210bc2f90a0916d6fb79324bb18741afee1206ad61e6c1618ff8a1f73b87a61a23ce04f1dc34a970ac3de

test:
  secret_key_base: f1bef118fd38f9014ba21163a14d26954c28dfbb3133021a99b8901de884d90e48af6ecc5161f038563498f12aa2eea67a5ff0640d9ec643c16cf2404ed50f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
